[package]
name = "hakoniwa-presentation"
version = "0.1.0"
edition = "2024"

[dependencies]
eframe = "0.36.2"
egui_tiles = { version = "0.17.1", default-features = false }
glam = "0.33.7"
hakoniwa-application = { version = "0.1.0", path = "../hakoniwa-application" }
hakoniwa-domain = { version = "0.1.0", path = "../hakoniwa-domain" }
